### ISSUE TITLE
No such metric Super Metric|sm_ff55995f-9a89-4a0f-a1ea-b04be95d3335

### ISSUE THREAD

**Issue by cleif** [notoriousbdg/vrops-dashboard-reclaimable_hosts#1]
Just deployed this dashboard into vROps, and this is the issue we are getting.
Version 8.0.1.15331180
Build 15331180
I've cleaned everything out and re-deployed to verify not a deployment issue.

**Comment by notoriousbdg** [comment]
Check the super metric named "Reclaimable Hosts by Memory" to ensure it's enabled for vSphere World, Datacenter, and Custom Datacenter object types.
